import { Button, VerticalBox } from "std-widgets.slint";
import { ToolsContainer } from "tools-container.slint";
import { FormatConverterContainer } from "format-converter-container.slint";

export component AppWindow inherits Window {
    property <int> idContainer: 0;
    if(idContainer == 0):ToolsContainer{
        idContainer: root.idContainer;
    }
    if(idContainer == 1):FormatConverterContainer {
        idContainer: root.idContainer;
    }
}
