import { ComboBox, TextEdit, VerticalBox, Button } from "std-widgets.slint";

export component FormatConverterContainer inherits Rectangle {
    in-out property <int> idContainer;
    in-out property <int> inputFormat;
    in-out property <int> outputFormat;
    in-out property <string> inputText;
    in-out property <string> outputText;

    callback format-converter-execute();
    callback format-converter-inverter();

    VerticalBox {
        HorizontalLayout {
            height: 50px;
            VerticalBox {
                Button {
                    width: 100%;
                    height: 50px;
                    text: "←";
                    clicked => {
                        root.idContainer = 0;
                    }
                }
            }
        }

        HorizontalLayout {
            height: 50px;
            VerticalBox {
                width: 45%;
                ComboBox {
                    height: 50px;
                    model: ["JSON", "CSV", "YAML", "XML"];
                    current-index <=> root.inputFormat;
                }
            }

            VerticalBox {
                width: 10%;
                Button {
                    height: 50px;
                    text: "↔";
                    clicked => root.format-converter-inverter();
                }
            }

            VerticalBox {
                width: 45%;
                ComboBox {
                    height: 50px;
                    model: ["JSON", "CSV", "YAML", "XML"];
                    current-index <=> root.outputFormat;
                }
            }
        }

        HorizontalLayout {
            VerticalBox {
                width: 45%;
                TextEdit {
                    text <=> root.inputText;
                }
            }

            VerticalBox {
                width: 10%;
                alignment: center;
                Button {
                    text: "→";
                    clicked => root.format-converter-execute();
                }
            }

            VerticalBox {
                width: 45%;
                TextEdit {
                    text <=> root.outputText;
                    read-only: true;
                }
            }
        }
    }
}
