import {
    ScrollView,
    VerticalBox,
    HorizontalBox,
    ComboBox,
} from "std-widgets.slint";
import { ItemCard } from "component/item-card.slint";

export component ToolsContainer inherits Rectangle {
    in-out property <int> idContainer;

    callback change-language(lang: string);

    background: transparent;
    border-radius: 6px;

    FocusScope {
        width: parent.width;
        height: parent.height;

        // lista visual
        ScrollView {
            width: parent.width;
            height: parent.height;
            mouse-drag-pan-enabled: true;
            VerticalBox {
                width: 90%;
                spacing: 10px;
                Text {
                    height: 20px;
                    text: @tr("Select Language:");
                    font-size: 16px;
                }

                ComboBox {
                    width: parent.width;
                    height: 50px;
                    model: ["---", "English", "Português Brasileiro"];
                    selected(value) => {
                        change-language(value);
                    }
                }

                Rectangle {
                    width: parent.width;
                    height: 2px;
                    background: #2c2f38;
                }

                Text {
                    height: 20px;
                    text: @tr("Tools");
                    font-size: 16px;
                    horizontal-alignment: center;
                }

                HorizontalBox {
                    ItemCard {
                        idContainer <=> root.idContainer;
                        cardId: 1;
                        icon: @image-url("images/icons/text_format_icon.svg");
                        name: @tr("Text Format Converter");
                    }

                    ItemCard {
                        idContainer <=> root.idContainer;
                        cardId: 2;
                        icon: @image-url("images/icons/file_verify_icon.svg");
                        name: @tr("File Verify");
                    }

                    ItemCard {
                        idContainer <=> root.idContainer;
                        cardId: 3;
                        icon: @image-url("images/icons/hdoc_request_icon.svg");
                        name: @tr("Request test with hdoc");
                    }
                }
            }
        }
    }
}
