import { ScrollView, VerticalBox, HorizontalBox } from "std-widgets.slint";

// Estrutura de dados para cada item da lista
export struct ItemRow {
    id: int,
    name: string
}

export component ToolsContainer inherits Rectangle {
    in-out property <int> idContainer;
    in property <[ItemRow]> rows: [
        // Exemplo de dados iniciais
        { id: 0, name: "Item 1" },
        { id: 1, name: "Item 2" },
    ];

    background: transparent;
    border-radius: 6px;

    FocusScope {
        width: parent.width;
        height: parent.height;

        // lista visual
        ScrollView  {
            width: parent.width;
            height: parent.height;
            mouse-drag-pan-enabled: true;
            VerticalBox {
                width: parent.width;
                spacing: 0px;
                for row[i] in rows: Rectangle {
                    border-radius: 15px;
                    background: ((Math.mod(i, 2) == 0) ? #10141c : #0b0f17);
                    HorizontalBox {
                        Image {
                            source: @image-url("home_icon.svg");
                            colorize: #ffffff;
                        }
                        Text {
                            vertical-alignment: center;
                            text: "MD5";
                            font-size:  30px;
                        }
                    }

                    TouchArea {
                        clicked => {
                            root.idContainer = row.id;
                        }
                    }
                }
            }
        }
    }
}