import {
    ScrollView,
    VerticalBox,
    HorizontalBox,
    ComboBox,
} from "std-widgets.slint";

export component ToolsContainer inherits Rectangle {
    in-out property <int> idContainer;

    callback change-language(lang: string);

    background: transparent;
    border-radius: 6px;

    FocusScope {
        width: parent.width;
        height: parent.height;

        // lista visual
        ScrollView {
            width: parent.width;
            height: parent.height;
            mouse-drag-pan-enabled: true;
            VerticalBox {
                width: 90%;
                spacing: 10px;
                Text {
                    height: 20px;
                    text: @tr("Select Language:");
                    font-size: 16px;
                }

                ComboBox {
                    width: parent.width;
                    height: 50px;
                    model: ["---", "English", "Português Brasileiro"];
                    selected(value) => {
                        change-language(value);
                    }
                }

                Rectangle {
                    width: parent.width;
                    height: 2px;
                    background: #2c2f38;
                }

                Text {
                    height: 20px;
                    text: @tr("Tools");
                    font-size: 16px;
                    horizontal-alignment: center;
                }

                HorizontalBox {
                    Rectangle {
                        border-radius: 15px;
                        width: 200px;
                        height: 200px;
                        background: #10141c;
                        HorizontalBox {
                            VerticalBox {
                                HorizontalBox {
                                    alignment: center;
                                    Image {
                                        source: @image-url("images/icons/text_format_icon.svg");
                                        colorize: #ffffff;
                                        width: 100px;
                                        height: 100px;
                                    }
                                }

                                Text {
                                    width: 90%;
                                    horizontal-alignment: center;
                                    text: @tr("Text Format Converter");
                                    font-size: 18px;
                                    wrap: TextWrap.word-wrap;
                                }
                            }
                        }

                        TouchArea {
                            clicked => {
                                root.idContainer = 1;
                            }
                        }
                    }

                    Rectangle {
                        border-radius: 15px;
                        width: 200px;
                        height: 200px;
                        background: #10141c;
                        HorizontalBox {
                            VerticalBox {
                                HorizontalBox {
                                    alignment: center;
                                    Image {
                                        source: @image-url("images/icons/file_verify_icon.svg");
                                        colorize: #ffffff;
                                        width: 100px;
                                        height: 100px;
                                    }
                                }

                                Text {
                                    width: 90%;
                                    horizontal-alignment: center;
                                    text: @tr("File Verify");
                                    font-size: 18px;
                                    wrap: TextWrap.word-wrap;
                                }
                            }
                        }

                        TouchArea {
                            clicked => {
                                root.idContainer = 2;
                            }
                        }
                    }
                }
            }
        }
    }
}
